In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pwd

'/home/ozkan/Desktop/rl_ws/src/scripts/research'

In [20]:
path="../Data/softmax/Hyperparam_opt_logs_"
summary=[]
for i in range(1,16):
    result_path=path+str(i)+"/test_results.csv"
    data=pd.read_csv(result_path)
    test_results={}
    test_results["test_number"]=data["test_number"].max()
    test_results["success_rate"]=(data["success"]).mean()
    test_results["obstacle_collision"]=(data["obstacle"]).mean()
    test_results["experiment_duration"]=(data["experiment_duration"]).mean()

    summary.append(test_results)   
summary=pd.DataFrame(summary)
summary

# data

    test_number  success_rate  obstacle_collision  experiment_duration
0            10           0.0                79.0              60.0000
1            10           0.0               107.3              60.0000
2            10           1.0                57.5              43.6141
3            10           0.0                80.6              60.0000
4            10           0.9                67.8              49.3723
5            10           1.0                55.5              43.7139
6            10           1.0                56.3              43.8141
7            10           0.6                74.2              49.8176
8            10           0.4                91.8              53.7164
9            10           0.0                96.1              60.0000
10           10           1.0                57.5              44.0123
11           10           0.9                58.6              45.1275
12           10           0.0               100.9              60.0000
13           10           0.9                77.4              45.5796
14           10           1.0                57.0              43.9484